name: First Workflow
# event
# Allows you to run this workflow manually from the Actions tab
on: workflow_dispatch
jobs:
  first-job:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: Print goodbye
        run: echo "Done"
